/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GTFSV2_REALTIME_GTFS_REALTIME_PB_H_INCLUDED
#define PB_GTFSV2_REALTIME_GTFS_REALTIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Determines whether the current fetch is incremental.  Currently,
 DIFFERENTIAL mode is unsupported and behavior is unspecified for feeds
 that use this mode.  There are discussions on the GTFS Realtime mailing
 list around fully specifying the behavior of DIFFERENTIAL mode and the
 documentation will be updated when those discussions are finalized. */
typedef enum _GTFSv2_Realtime_FeedHeader_Incrementality {
    GTFSv2_Realtime_FeedHeader_Incrementality_FULL_DATASET = 0,
    GTFSv2_Realtime_FeedHeader_Incrementality_DIFFERENTIAL = 1
} GTFSv2_Realtime_FeedHeader_Incrementality;

/* The relation between this StopTime and the static schedule. */
typedef enum _GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship {
    /* The vehicle is proceeding in accordance with its static schedule of
 stops, although not necessarily according to the times of the schedule.
 At least one of arrival and departure must be provided. If the schedule
 for this stop contains both arrival and departure times then so must
 this update. Frequency-based trips (GTFS frequencies.txt with exact_times = 0)
 should not have a SCHEDULED value and should use UNSCHEDULED instead. */
    GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_SCHEDULED = 0,
    /* The stop is skipped, i.e., the vehicle will not stop at this stop.
 Arrival and departure are optional. */
    GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_SKIPPED = 1,
    /* No data is given for this stop. The main intention for this value is to
 give the predictions only for part of a trip, i.e., if the last update
 for a trip has a NO_DATA specifier, then StopTimes for the rest of the
 stops in the trip are considered to be unspecified as well.
 Neither arrival nor departure should be supplied. */
    GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_NO_DATA = 2,
    /* The vehicle is operating a trip defined in GTFS frequencies.txt with exact_times = 0.
 This value should not be used for trips that are not defined in GTFS frequencies.txt,
 or trips in GTFS frequencies.txt with exact_times = 1. Trips containing StopTimeUpdates
 with ScheduleRelationship=UNSCHEDULED must also set TripDescriptor.ScheduleRelationship=UNSCHEDULED.
 NOTE: This field is still experimental, and subject to change. It may be
 formally adopted in the future. */
    GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_UNSCHEDULED = 3
} GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship;

typedef enum _GTFSv2_Realtime_VehiclePosition_VehicleStopStatus {
    /* The vehicle is just about to arrive at the stop (on a stop
 display, the vehicle symbol typically flashes). */
    GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_INCOMING_AT = 0,
    /* The vehicle is standing at the stop. */
    GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_STOPPED_AT = 1,
    /* The vehicle has departed and is in transit to the next stop. */
    GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_IN_TRANSIT_TO = 2
} GTFSv2_Realtime_VehiclePosition_VehicleStopStatus;

/* Congestion level that is affecting this vehicle. */
typedef enum _GTFSv2_Realtime_VehiclePosition_CongestionLevel {
    GTFSv2_Realtime_VehiclePosition_CongestionLevel_UNKNOWN_CONGESTION_LEVEL = 0,
    GTFSv2_Realtime_VehiclePosition_CongestionLevel_RUNNING_SMOOTHLY = 1,
    GTFSv2_Realtime_VehiclePosition_CongestionLevel_STOP_AND_GO = 2,
    GTFSv2_Realtime_VehiclePosition_CongestionLevel_CONGESTION = 3,
    GTFSv2_Realtime_VehiclePosition_CongestionLevel_SEVERE_CONGESTION = 4 /* People leaving their cars. */
} GTFSv2_Realtime_VehiclePosition_CongestionLevel;

/* The degree of passenger occupancy of the vehicle. This field is still
 experimental, and subject to change. It may be formally adopted in the
 future. */
typedef enum _GTFSv2_Realtime_VehiclePosition_OccupancyStatus {
    /* The vehicle is considered empty by most measures, and has few or no
 passengers onboard, but is still accepting passengers. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_EMPTY = 0,
    /* The vehicle has a relatively large percentage of seats available.
 What percentage of free seats out of the total seats available is to be
 considered large enough to fall into this category is determined at the
 discretion of the producer. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_MANY_SEATS_AVAILABLE = 1,
    /* The vehicle has a relatively small percentage of seats available.
 What percentage of free seats out of the total seats available is to be
 considered small enough to fall into this category is determined at the
 discretion of the feed producer. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_FEW_SEATS_AVAILABLE = 2,
    /* The vehicle can currently accommodate only standing passengers. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_STANDING_ROOM_ONLY = 3,
    /* The vehicle can currently accommodate only standing passengers
 and has limited space for them. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_CRUSHED_STANDING_ROOM_ONLY = 4,
    /* The vehicle is considered full by most measures, but may still be
 allowing passengers to board. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_FULL = 5,
    /* The vehicle is not accepting additional passengers. */
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus_NOT_ACCEPTING_PASSENGERS = 6
} GTFSv2_Realtime_VehiclePosition_OccupancyStatus;

/* Cause of this alert. */
typedef enum _GTFSv2_Realtime_Alert_Cause {
    GTFSv2_Realtime_Alert_Cause_UNKNOWN_CAUSE = 1,
    GTFSv2_Realtime_Alert_Cause_OTHER_CAUSE = 2, /* Not machine-representable. */
    GTFSv2_Realtime_Alert_Cause_TECHNICAL_PROBLEM = 3,
    GTFSv2_Realtime_Alert_Cause_STRIKE = 4, /* Public transit agency employees stopped working. */
    GTFSv2_Realtime_Alert_Cause_DEMONSTRATION = 5, /* People are blocking the streets. */
    GTFSv2_Realtime_Alert_Cause_ACCIDENT = 6,
    GTFSv2_Realtime_Alert_Cause_HOLIDAY = 7,
    GTFSv2_Realtime_Alert_Cause_WEATHER = 8,
    GTFSv2_Realtime_Alert_Cause_MAINTENANCE = 9,
    GTFSv2_Realtime_Alert_Cause_CONSTRUCTION = 10,
    GTFSv2_Realtime_Alert_Cause_POLICE_ACTIVITY = 11,
    GTFSv2_Realtime_Alert_Cause_MEDICAL_EMERGENCY = 12
} GTFSv2_Realtime_Alert_Cause;

/* What is the effect of this problem on the affected entity. */
typedef enum _GTFSv2_Realtime_Alert_Effect {
    GTFSv2_Realtime_Alert_Effect_NO_SERVICE = 1,
    GTFSv2_Realtime_Alert_Effect_REDUCED_SERVICE = 2,
    /* We don't care about INsignificant delays: they are hard to detect, have
 little impact on the user, and would clutter the results as they are too
 frequent. */
    GTFSv2_Realtime_Alert_Effect_SIGNIFICANT_DELAYS = 3,
    GTFSv2_Realtime_Alert_Effect_DETOUR = 4,
    GTFSv2_Realtime_Alert_Effect_ADDITIONAL_SERVICE = 5,
    GTFSv2_Realtime_Alert_Effect_MODIFIED_SERVICE = 6,
    GTFSv2_Realtime_Alert_Effect_OTHER_EFFECT = 7,
    GTFSv2_Realtime_Alert_Effect_UNKNOWN_EFFECT = 8,
    GTFSv2_Realtime_Alert_Effect_STOP_MOVED = 9,
    GTFSv2_Realtime_Alert_Effect_NO_EFFECT = 10,
    GTFSv2_Realtime_Alert_Effect_ACCESSIBILITY_ISSUE = 11
} GTFSv2_Realtime_Alert_Effect;

/* Severity of this alert. */
typedef enum _GTFSv2_Realtime_Alert_SeverityLevel {
    GTFSv2_Realtime_Alert_SeverityLevel_UNKNOWN_SEVERITY = 1,
    GTFSv2_Realtime_Alert_SeverityLevel_INFO = 2,
    GTFSv2_Realtime_Alert_SeverityLevel_WARNING = 3,
    GTFSv2_Realtime_Alert_SeverityLevel_SEVERE = 4
} GTFSv2_Realtime_Alert_SeverityLevel;

/* The relation between this trip and the static schedule. If a trip is done
 in accordance with temporary schedule, not reflected in GTFS, then it
 shouldn't be marked as SCHEDULED, but likely as ADDED. */
typedef enum _GTFSv2_Realtime_TripDescriptor_ScheduleRelationship {
    /* Trip that is running in accordance with its GTFS schedule, or is close
 enough to the scheduled trip to be associated with it. */
    GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_SCHEDULED = 0,
    /* An extra trip that was added in addition to a running schedule, for
 example, to replace a broken vehicle or to respond to sudden passenger
 load. */
    GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_ADDED = 1,
    /* A trip that is running with no schedule associated to it (GTFS frequencies.txt exact_times=0).
 Trips with ScheduleRelationship=UNSCHEDULED must also set all StopTimeUpdates.ScheduleRelationship=UNSCHEDULED. */
    GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_UNSCHEDULED = 2,
    /* A trip that existed in the schedule but was removed. */
    GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_CANCELED = 3,
    /* Should not be used - for backwards-compatibility only. */
    GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_REPLACEMENT = 5
} GTFSv2_Realtime_TripDescriptor_ScheduleRelationship;

/* Struct definitions */
/* Metadata about a feed, included in feed messages. */
typedef struct _GTFSv2_Realtime_FeedHeader {
    /* Version of the feed specification.
 The current version is 2.0.  Valid versions are "2.0", "1.0". */
    pb_callback_t gtfs_realtime_version;
    bool has_incrementality;
    GTFSv2_Realtime_FeedHeader_Incrementality incrementality;
    /* This timestamp identifies the moment when the content of this feed has been
 created (in server time). In POSIX time (i.e., number of seconds since
 January 1st 1970 00:00:00 UTC). */
    bool has_timestamp;
    uint64_t timestamp;
    pb_extension_t *extensions;
} GTFSv2_Realtime_FeedHeader;

/* The contents of a feed message.
 A feed is a continuous stream of feed messages. Each message in the stream is
 obtained as a response to an appropriate HTTP GET request.
 A realtime feed is always defined with relation to an existing GTFS feed.
 All the entity ids are resolved with respect to the GTFS feed.
 Note that "required" and "optional" as stated in this file refer to Protocol
 Buffer cardinality, not semantic cardinality.  See reference.md at
 https://github.com/google/transit/tree/master/gtfs-realtime for field
 semantic cardinality. */
typedef struct _GTFSv2_Realtime_FeedMessage {
    /* Metadata about this feed and feed message. */
    GTFSv2_Realtime_FeedHeader header;
    /* Contents of the feed. */
    pb_callback_t entity;
    pb_extension_t *extensions;
} GTFSv2_Realtime_FeedMessage;

/* Timing information for a single predicted event (either arrival or
 departure).
 Timing consists of delay and/or estimated time, and uncertainty.
 - delay should be used when the prediction is given relative to some
   existing schedule in GTFS.
 - time should be given whether there is a predicted schedule or not. If
   both time and delay are specified, time will take precedence
   (although normally, time, if given for a scheduled trip, should be
   equal to scheduled time in GTFS + delay).

 Uncertainty applies equally to both time and delay.
 The uncertainty roughly specifies the expected error in true delay (but
 note, we don't yet define its precise statistical meaning). It's possible
 for the uncertainty to be 0, for example for trains that are driven under
 computer timing control. */
typedef struct _GTFSv2_Realtime_TripUpdate_StopTimeEvent {
    /* Delay (in seconds) can be positive (meaning that the vehicle is late) or
 negative (meaning that the vehicle is ahead of schedule). Delay of 0
 means that the vehicle is exactly on time. */
    bool has_delay;
    int32_t delay;
    /* Event as absolute time.
 In Unix time (i.e., number of seconds since January 1st 1970 00:00:00
 UTC). */
    bool has_time;
    int64_t time;
    /* If uncertainty is omitted, it is interpreted as unknown.
 If the prediction is unknown or too uncertain, the delay (or time) field
 should be empty. In such case, the uncertainty field is ignored.
 To specify a completely certain prediction, set its uncertainty to 0. */
    bool has_uncertainty;
    int32_t uncertainty;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TripUpdate_StopTimeEvent;

/* Realtime update for arrival and/or departure events for a given stop on a
 trip. Updates can be supplied for both past and future events.
 The producer is allowed, although not required, to drop past events. */
typedef struct _GTFSv2_Realtime_TripUpdate_StopTimeUpdate { /* The update is linked to a specific stop either through stop_sequence or
 stop_id, so one of the fields below must necessarily be set.
 See the documentation in TripDescriptor for more information. */
    /* Must be the same as in stop_times.txt in the corresponding GTFS feed. */
    bool has_stop_sequence;
    uint32_t stop_sequence;
    bool has_arrival;
    GTFSv2_Realtime_TripUpdate_StopTimeEvent arrival;
    bool has_departure;
    GTFSv2_Realtime_TripUpdate_StopTimeEvent departure;
    /* Must be the same as in stops.txt in the corresponding GTFS feed. */
    pb_callback_t stop_id;
    bool has_schedule_relationship;
    GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship schedule_relationship;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TripUpdate_StopTimeUpdate;

/* A time interval. The interval is considered active at time 't' if 't' is
 greater than or equal to the start time and less than the end time. */
typedef struct _GTFSv2_Realtime_TimeRange {
    /* Start time, in POSIX time (i.e., number of seconds since January 1st 1970
 00:00:00 UTC).
 If missing, the interval starts at minus infinity. */
    bool has_start;
    uint64_t start;
    /* End time, in POSIX time (i.e., number of seconds since January 1st 1970
 00:00:00 UTC).
 If missing, the interval ends at plus infinity. */
    bool has_end;
    uint64_t end;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TimeRange;

/* A position. */
typedef struct _GTFSv2_Realtime_Position {
    /* Degrees North, in the WGS-84 coordinate system. */
    float latitude;
    /* Degrees East, in the WGS-84 coordinate system. */
    float longitude;
    /* Bearing, in degrees, clockwise from North, i.e., 0 is North and 90 is East.
 This can be the compass bearing, or the direction towards the next stop
 or intermediate location.
 This should not be direction deduced from the sequence of previous
 positions, which can be computed from previous data. */
    bool has_bearing;
    float bearing;
    /* Odometer value, in meters. */
    bool has_odometer;
    double odometer;
    /* Momentary speed measured by the vehicle, in meters per second. */
    bool has_speed;
    float speed;
    pb_extension_t *extensions;
} GTFSv2_Realtime_Position;

/* A descriptor that identifies an instance of a GTFS trip, or all instances of
 a trip along a route.
 - To specify a single trip instance, the trip_id (and if necessary,
   start_time) is set. If route_id is also set, then it should be same as one
   that the given trip corresponds to.
 - To specify all the trips along a given route, only the route_id should be
   set. Note that if the trip_id is not known, then stop sequence ids in
   TripUpdate are not sufficient, and stop_ids must be provided as well. In
   addition, absolute arrival/departure times must be provided. */
typedef struct _GTFSv2_Realtime_TripDescriptor {
    /* The trip_id from the GTFS feed that this selector refers to.
 For non frequency-based trips, this field is enough to uniquely identify
 the trip. For frequency-based trip, start_time and start_date might also be
 necessary. */
    pb_callback_t trip_id;
    /* The initially scheduled start time of this trip instance.
 When the trip_id corresponds to a non-frequency-based trip, this field
 should either be omitted or be equal to the value in the GTFS feed. When
 the trip_id correponds to a frequency-based trip, the start_time must be
 specified for trip updates and vehicle positions. If the trip corresponds
 to exact_times=1 GTFS record, then start_time must be some multiple
 (including zero) of headway_secs later than frequencies.txt start_time for
 the corresponding time period. If the trip corresponds to exact_times=0,
 then its start_time may be arbitrary, and is initially expected to be the
 first departure of the trip. Once established, the start_time of this
 frequency-based trip should be considered immutable, even if the first
 departure time changes -- that time change may instead be reflected in a
 StopTimeUpdate.
 Format and semantics of the field is same as that of
 GTFS/frequencies.txt/start_time, e.g., 11:15:35 or 25:15:35. */
    pb_callback_t start_time;
    /* The scheduled start date of this trip instance.
 Must be provided to disambiguate trips that are so late as to collide with
 a scheduled trip on a next day. For example, for a train that departs 8:00
 and 20:00 every day, and is 12 hours late, there would be two distinct
 trips on the same time.
 This field can be provided but is not mandatory for schedules in which such
 collisions are impossible - for example, a service running on hourly
 schedule where a vehicle that is one hour late is not considered to be
 related to schedule anymore.
 In YYYYMMDD format. */
    pb_callback_t start_date;
    bool has_schedule_relationship;
    GTFSv2_Realtime_TripDescriptor_ScheduleRelationship schedule_relationship;
    /* The route_id from the GTFS that this selector refers to. */
    pb_callback_t route_id;
    /* The direction_id from the GTFS feed trips.txt file, indicating the
 direction of travel for trips this selector refers to. */
    bool has_direction_id;
    uint32_t direction_id;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TripDescriptor;

/* Identification information for the vehicle performing the trip. */
typedef struct _GTFSv2_Realtime_VehicleDescriptor {
    /* Internal system identification of the vehicle. Should be unique per
 vehicle, and can be used for tracking the vehicle as it proceeds through
 the system. */
    pb_callback_t id;
    /* User visible label, i.e., something that must be shown to the passenger to
 help identify the correct vehicle. */
    pb_callback_t label;
    /* The license plate of the vehicle. */
    pb_callback_t license_plate;
    pb_extension_t *extensions;
} GTFSv2_Realtime_VehicleDescriptor;

/* Realtime update of the progress of a vehicle along a trip.
 Depending on the value of ScheduleRelationship, a TripUpdate can specify:
 - A trip that proceeds along the schedule.
 - A trip that proceeds along a route but has no fixed schedule.
 - A trip that have been added or removed with regard to schedule.

 The updates can be for future, predicted arrival/departure events, or for
 past events that already occurred.
 Normally, updates should get more precise and more certain (see
 uncertainty below) as the events gets closer to current time.
 Even if that is not possible, the information for past events should be
 precise and certain. In particular, if an update points to time in the past
 but its update's uncertainty is not 0, the client should conclude that the
 update is a (wrong) prediction and that the trip has not completed yet.

 Note that the update can describe a trip that is already completed.
 To this end, it is enough to provide an update for the last stop of the trip.
 If the time of that is in the past, the client will conclude from that that
 the whole trip is in the past (it is possible, although inconsequential, to
 also provide updates for preceding stops).
 This option is most relevant for a trip that has completed ahead of schedule,
 but according to the schedule, the trip is still proceeding at the current
 time. Removing the updates for this trip could make the client assume
 that the trip is still proceeding.
 Note that the feed provider is allowed, but not required, to purge past
 updates - this is one case where this would be practically useful. */
typedef struct _GTFSv2_Realtime_TripUpdate {
    /* The Trip that this message applies to. There can be at most one
 TripUpdate entity for each actual trip instance.
 If there is none, that means there is no prediction information available.
 It does *not* mean that the trip is progressing according to schedule. */
    GTFSv2_Realtime_TripDescriptor trip;
    /* Updates to StopTimes for the trip (both future, i.e., predictions, and in
 some cases, past ones, i.e., those that already happened).
 The updates must be sorted by stop_sequence, and apply for all the
 following stops of the trip up to the next specified one.

 Example 1:
 For a trip with 20 stops, a StopTimeUpdate with arrival delay and departure
 delay of 0 for stop_sequence of the current stop means that the trip is
 exactly on time.

 Example 2:
 For the same trip instance, 3 StopTimeUpdates are provided:
 - delay of 5 min for stop_sequence 3
 - delay of 1 min for stop_sequence 8
 - delay of unspecified duration for stop_sequence 10
 This will be interpreted as:
 - stop_sequences 3,4,5,6,7 have delay of 5 min.
 - stop_sequences 8,9 have delay of 1 min.
 - stop_sequences 10,... have unknown delay. */
    pb_callback_t stop_time_update;
    /* Additional information on the vehicle that is serving this trip. */
    bool has_vehicle;
    GTFSv2_Realtime_VehicleDescriptor vehicle;
    /* Moment at which the vehicle's real-time progress was measured. In POSIX
 time (i.e., the number of seconds since January 1st 1970 00:00:00 UTC). */
    bool has_timestamp;
    uint64_t timestamp;
    /* The current schedule deviation for the trip.  Delay should only be
 specified when the prediction is given relative to some existing schedule
 in GTFS.

 Delay (in seconds) can be positive (meaning that the vehicle is late) or
 negative (meaning that the vehicle is ahead of schedule). Delay of 0
 means that the vehicle is exactly on time.

 Delay information in StopTimeUpdates take precedent of trip-level delay
 information, such that trip-level delay is only propagated until the next
 stop along the trip with a StopTimeUpdate delay value specified.

 Feed providers are strongly encouraged to provide a TripUpdate.timestamp
 value indicating when the delay value was last updated, in order to
 evaluate the freshness of the data.

 NOTE: This field is still experimental, and subject to change. It may be
 formally adopted in the future. */
    bool has_delay;
    int32_t delay;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TripUpdate;

/* Realtime positioning information for a given vehicle. */
typedef struct _GTFSv2_Realtime_VehiclePosition {
    /* The Trip that this vehicle is serving.
 Can be empty or partial if the vehicle can not be identified with a given
 trip instance. */
    bool has_trip;
    GTFSv2_Realtime_TripDescriptor trip;
    /* Current position of this vehicle. */
    bool has_position;
    GTFSv2_Realtime_Position position;
    /* The stop sequence index of the current stop. The meaning of
 current_stop_sequence (i.e., the stop that it refers to) is determined by
 current_status.
 If current_status is missing IN_TRANSIT_TO is assumed. */
    bool has_current_stop_sequence;
    uint32_t current_stop_sequence;
    /* The exact status of the vehicle with respect to the current stop.
 Ignored if current_stop_sequence is missing. */
    bool has_current_status;
    GTFSv2_Realtime_VehiclePosition_VehicleStopStatus current_status;
    /* Moment at which the vehicle's position was measured. In POSIX time
 (i.e., number of seconds since January 1st 1970 00:00:00 UTC). */
    bool has_timestamp;
    uint64_t timestamp;
    bool has_congestion_level;
    GTFSv2_Realtime_VehiclePosition_CongestionLevel congestion_level;
    /* Identifies the current stop. The value must be the same as in stops.txt in
 the corresponding GTFS feed. */
    pb_callback_t stop_id;
    /* Additional information on the vehicle that is serving this trip. */
    bool has_vehicle;
    GTFSv2_Realtime_VehicleDescriptor vehicle;
    bool has_occupancy_status;
    GTFSv2_Realtime_VehiclePosition_OccupancyStatus occupancy_status;
    /* A percentage value representing the degree of passenger occupancy of the vehicle.
 The values are represented as an integer without decimals. 0 means 0% and 100 means 100%.
 The value 100 should represent the total maximum occupancy the vehicle was designed for,
 including both seated and standing capacity, and current operating regulations allow.
 It is possible that the value goes over 100 if there are currently more passengers than what the vehicle was designed for.
 The precision of occupancy_percentage should be low enough that you can't track a single person boarding and alighting for privacy reasons.
 This field is still experimental, and subject to change. It may be formally adopted in the future. */
    bool has_occupancy_percentage;
    uint32_t occupancy_percentage;
    pb_extension_t *extensions;
} GTFSv2_Realtime_VehiclePosition;

/* A selector for an entity in a GTFS feed. */
typedef struct _GTFSv2_Realtime_EntitySelector {
    /* The values of the fields should correspond to the appropriate fields in the
 GTFS feed.
 At least one specifier must be given. If several are given, then the
 matching has to apply to all the given specifiers. */
    pb_callback_t agency_id;
    pb_callback_t route_id;
    /* corresponds to route_type in GTFS. */
    bool has_route_type;
    int32_t route_type;
    bool has_trip;
    GTFSv2_Realtime_TripDescriptor trip;
    pb_callback_t stop_id;
    /* Corresponds to trip direction_id in GTFS trips.txt. If provided the
 route_id must also be provided. */
    bool has_direction_id;
    uint32_t direction_id;
    pb_extension_t *extensions;
} GTFSv2_Realtime_EntitySelector;

/* An internationalized message containing per-language versions of a snippet of
 text or a URL.
 One of the strings from a message will be picked up. The resolution proceeds
 as follows:
 1. If the UI language matches the language code of a translation,
    the first matching translation is picked.
 2. If a default UI language (e.g., English) matches the language code of a
    translation, the first matching translation is picked.
 3. If some translation has an unspecified language code, that translation is
    picked. */
typedef struct _GTFSv2_Realtime_TranslatedString {
    /* At least one translation must be provided. */
    pb_callback_t translation;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TranslatedString;

/* An alert, indicating some sort of incident in the public transit network. */
typedef struct _GTFSv2_Realtime_Alert {
    /* Time when the alert should be shown to the user. If missing, the
 alert will be shown as long as it appears in the feed.
 If multiple ranges are given, the alert will be shown during all of them. */
    pb_callback_t active_period;
    /* Entities whose users we should notify of this alert. */
    pb_callback_t informed_entity;
    bool has_cause;
    GTFSv2_Realtime_Alert_Cause cause;
    bool has_effect;
    GTFSv2_Realtime_Alert_Effect effect;
    /* The URL which provides additional information about the alert. */
    bool has_url;
    GTFSv2_Realtime_TranslatedString url;
    /* Alert header. Contains a short summary of the alert text as plain-text. */
    bool has_header_text;
    GTFSv2_Realtime_TranslatedString header_text;
    /* Full description for the alert as plain-text. The information in the
 description should add to the information of the header. */
    bool has_description_text;
    GTFSv2_Realtime_TranslatedString description_text;
    /* Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
 This field is still experimental, and subject to change. It may be formally adopted in the future. */
    bool has_tts_header_text;
    GTFSv2_Realtime_TranslatedString tts_header_text;
    /* Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
 This field is still experimental, and subject to change. It may be formally adopted in the future. */
    bool has_tts_description_text;
    GTFSv2_Realtime_TranslatedString tts_description_text;
    bool has_severity_level;
    GTFSv2_Realtime_Alert_SeverityLevel severity_level;
    pb_extension_t *extensions;
} GTFSv2_Realtime_Alert;

/* A definition (or update) of an entity in the transit feed. */
typedef struct _GTFSv2_Realtime_FeedEntity {
    /* The ids are used only to provide incrementality support. The id should be
 unique within a FeedMessage. Consequent FeedMessages may contain
 FeedEntities with the same id. In case of a DIFFERENTIAL update the new
 FeedEntity with some id will replace the old FeedEntity with the same id
 (or delete it - see is_deleted below).
 The actual GTFS entities (e.g. stations, routes, trips) referenced by the
 feed must be specified by explicit selectors (see EntitySelector below for
 more info). */
    pb_callback_t id;
    /* Whether this entity is to be deleted. Relevant only for incremental
 fetches. */
    bool has_is_deleted;
    bool is_deleted;
    /* Data about the entity itself. Exactly one of the following fields must be
 present (unless the entity is being deleted). */
    bool has_trip_update;
    GTFSv2_Realtime_TripUpdate trip_update;
    bool has_vehicle;
    GTFSv2_Realtime_VehiclePosition vehicle;
    bool has_alert;
    GTFSv2_Realtime_Alert alert;
    pb_extension_t *extensions;
} GTFSv2_Realtime_FeedEntity;

typedef struct _GTFSv2_Realtime_TranslatedString_Translation {
    /* A UTF-8 string containing the message. */
    pb_callback_t text;
    /* BCP-47 language code. Can be omitted if the language is unknown or if
 no i18n is done at all for the feed. At most one translation is
 allowed to have an unspecified language tag. */
    pb_callback_t language;
    pb_extension_t *extensions;
} GTFSv2_Realtime_TranslatedString_Translation;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _GTFSv2_Realtime_FeedHeader_Incrementality_MIN GTFSv2_Realtime_FeedHeader_Incrementality_FULL_DATASET
#define _GTFSv2_Realtime_FeedHeader_Incrementality_MAX GTFSv2_Realtime_FeedHeader_Incrementality_DIFFERENTIAL
#define _GTFSv2_Realtime_FeedHeader_Incrementality_ARRAYSIZE ((GTFSv2_Realtime_FeedHeader_Incrementality)(GTFSv2_Realtime_FeedHeader_Incrementality_DIFFERENTIAL+1))

#define _GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_MIN GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_SCHEDULED
#define _GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_MAX GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_UNSCHEDULED
#define _GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_ARRAYSIZE ((GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship)(GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_UNSCHEDULED+1))

#define _GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_MIN GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_INCOMING_AT
#define _GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_MAX GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_IN_TRANSIT_TO
#define _GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_ARRAYSIZE ((GTFSv2_Realtime_VehiclePosition_VehicleStopStatus)(GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_IN_TRANSIT_TO+1))

#define _GTFSv2_Realtime_VehiclePosition_CongestionLevel_MIN GTFSv2_Realtime_VehiclePosition_CongestionLevel_UNKNOWN_CONGESTION_LEVEL
#define _GTFSv2_Realtime_VehiclePosition_CongestionLevel_MAX GTFSv2_Realtime_VehiclePosition_CongestionLevel_SEVERE_CONGESTION
#define _GTFSv2_Realtime_VehiclePosition_CongestionLevel_ARRAYSIZE ((GTFSv2_Realtime_VehiclePosition_CongestionLevel)(GTFSv2_Realtime_VehiclePosition_CongestionLevel_SEVERE_CONGESTION+1))

#define _GTFSv2_Realtime_VehiclePosition_OccupancyStatus_MIN GTFSv2_Realtime_VehiclePosition_OccupancyStatus_EMPTY
#define _GTFSv2_Realtime_VehiclePosition_OccupancyStatus_MAX GTFSv2_Realtime_VehiclePosition_OccupancyStatus_NOT_ACCEPTING_PASSENGERS
#define _GTFSv2_Realtime_VehiclePosition_OccupancyStatus_ARRAYSIZE ((GTFSv2_Realtime_VehiclePosition_OccupancyStatus)(GTFSv2_Realtime_VehiclePosition_OccupancyStatus_NOT_ACCEPTING_PASSENGERS+1))

#define _GTFSv2_Realtime_Alert_Cause_MIN GTFSv2_Realtime_Alert_Cause_UNKNOWN_CAUSE
#define _GTFSv2_Realtime_Alert_Cause_MAX GTFSv2_Realtime_Alert_Cause_MEDICAL_EMERGENCY
#define _GTFSv2_Realtime_Alert_Cause_ARRAYSIZE ((GTFSv2_Realtime_Alert_Cause)(GTFSv2_Realtime_Alert_Cause_MEDICAL_EMERGENCY+1))

#define _GTFSv2_Realtime_Alert_Effect_MIN GTFSv2_Realtime_Alert_Effect_NO_SERVICE
#define _GTFSv2_Realtime_Alert_Effect_MAX GTFSv2_Realtime_Alert_Effect_ACCESSIBILITY_ISSUE
#define _GTFSv2_Realtime_Alert_Effect_ARRAYSIZE ((GTFSv2_Realtime_Alert_Effect)(GTFSv2_Realtime_Alert_Effect_ACCESSIBILITY_ISSUE+1))

#define _GTFSv2_Realtime_Alert_SeverityLevel_MIN GTFSv2_Realtime_Alert_SeverityLevel_UNKNOWN_SEVERITY
#define _GTFSv2_Realtime_Alert_SeverityLevel_MAX GTFSv2_Realtime_Alert_SeverityLevel_SEVERE
#define _GTFSv2_Realtime_Alert_SeverityLevel_ARRAYSIZE ((GTFSv2_Realtime_Alert_SeverityLevel)(GTFSv2_Realtime_Alert_SeverityLevel_SEVERE+1))

#define _GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_MIN GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_SCHEDULED
#define _GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_MAX GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_REPLACEMENT
#define _GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_ARRAYSIZE ((GTFSv2_Realtime_TripDescriptor_ScheduleRelationship)(GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_REPLACEMENT+1))


#define GTFSv2_Realtime_FeedHeader_incrementality_ENUMTYPE GTFSv2_Realtime_FeedHeader_Incrementality




#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_schedule_relationship_ENUMTYPE GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship

#define GTFSv2_Realtime_VehiclePosition_current_status_ENUMTYPE GTFSv2_Realtime_VehiclePosition_VehicleStopStatus
#define GTFSv2_Realtime_VehiclePosition_congestion_level_ENUMTYPE GTFSv2_Realtime_VehiclePosition_CongestionLevel
#define GTFSv2_Realtime_VehiclePosition_occupancy_status_ENUMTYPE GTFSv2_Realtime_VehiclePosition_OccupancyStatus

#define GTFSv2_Realtime_Alert_cause_ENUMTYPE GTFSv2_Realtime_Alert_Cause
#define GTFSv2_Realtime_Alert_effect_ENUMTYPE GTFSv2_Realtime_Alert_Effect
#define GTFSv2_Realtime_Alert_severity_level_ENUMTYPE GTFSv2_Realtime_Alert_SeverityLevel



#define GTFSv2_Realtime_TripDescriptor_schedule_relationship_ENUMTYPE GTFSv2_Realtime_TripDescriptor_ScheduleRelationship






/* Initializer values for message structs */
#define GTFSv2_Realtime_FeedMessage_init_default {GTFSv2_Realtime_FeedHeader_init_default, {{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_FeedHeader_init_default  {{{NULL}, NULL}, false, GTFSv2_Realtime_FeedHeader_Incrementality_FULL_DATASET, false, 0, NULL}
#define GTFSv2_Realtime_FeedEntity_init_default  {{{NULL}, NULL}, false, false, false, GTFSv2_Realtime_TripUpdate_init_default, false, GTFSv2_Realtime_VehiclePosition_init_default, false, GTFSv2_Realtime_Alert_init_default, NULL}
#define GTFSv2_Realtime_TripUpdate_init_default  {GTFSv2_Realtime_TripDescriptor_init_default, {{NULL}, NULL}, false, GTFSv2_Realtime_VehicleDescriptor_init_default, false, 0, false, 0, NULL}
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_init_default {false, 0, false, 0, false, 0, NULL}
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_init_default {false, 0, false, GTFSv2_Realtime_TripUpdate_StopTimeEvent_init_default, false, GTFSv2_Realtime_TripUpdate_StopTimeEvent_init_default, {{NULL}, NULL}, false, GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_SCHEDULED, NULL}
#define GTFSv2_Realtime_VehiclePosition_init_default {false, GTFSv2_Realtime_TripDescriptor_init_default, false, GTFSv2_Realtime_Position_init_default, false, 0, false, GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_IN_TRANSIT_TO, false, 0, false, _GTFSv2_Realtime_VehiclePosition_CongestionLevel_MIN, {{NULL}, NULL}, false, GTFSv2_Realtime_VehicleDescriptor_init_default, false, _GTFSv2_Realtime_VehiclePosition_OccupancyStatus_MIN, false, 0, NULL}
#define GTFSv2_Realtime_Alert_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, false, GTFSv2_Realtime_Alert_Cause_UNKNOWN_CAUSE, false, GTFSv2_Realtime_Alert_Effect_UNKNOWN_EFFECT, false, GTFSv2_Realtime_TranslatedString_init_default, false, GTFSv2_Realtime_TranslatedString_init_default, false, GTFSv2_Realtime_TranslatedString_init_default, false, GTFSv2_Realtime_TranslatedString_init_default, false, GTFSv2_Realtime_TranslatedString_init_default, false, GTFSv2_Realtime_Alert_SeverityLevel_UNKNOWN_SEVERITY, NULL}
#define GTFSv2_Realtime_TimeRange_init_default   {false, 0, false, 0, NULL}
#define GTFSv2_Realtime_Position_init_default    {0, 0, false, 0, false, 0, false, 0, NULL}
#define GTFSv2_Realtime_TripDescriptor_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_MIN, {{NULL}, NULL}, false, 0, NULL}
#define GTFSv2_Realtime_VehicleDescriptor_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_EntitySelector_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, GTFSv2_Realtime_TripDescriptor_init_default, {{NULL}, NULL}, false, 0, NULL}
#define GTFSv2_Realtime_TranslatedString_init_default {{{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_TranslatedString_Translation_init_default {{{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_FeedMessage_init_zero    {GTFSv2_Realtime_FeedHeader_init_zero, {{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_FeedHeader_init_zero     {{{NULL}, NULL}, false, _GTFSv2_Realtime_FeedHeader_Incrementality_MIN, false, 0, NULL}
#define GTFSv2_Realtime_FeedEntity_init_zero     {{{NULL}, NULL}, false, 0, false, GTFSv2_Realtime_TripUpdate_init_zero, false, GTFSv2_Realtime_VehiclePosition_init_zero, false, GTFSv2_Realtime_Alert_init_zero, NULL}
#define GTFSv2_Realtime_TripUpdate_init_zero     {GTFSv2_Realtime_TripDescriptor_init_zero, {{NULL}, NULL}, false, GTFSv2_Realtime_VehicleDescriptor_init_zero, false, 0, false, 0, NULL}
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_init_zero {false, 0, false, 0, false, 0, NULL}
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_init_zero {false, 0, false, GTFSv2_Realtime_TripUpdate_StopTimeEvent_init_zero, false, GTFSv2_Realtime_TripUpdate_StopTimeEvent_init_zero, {{NULL}, NULL}, false, _GTFSv2_Realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_MIN, NULL}
#define GTFSv2_Realtime_VehiclePosition_init_zero {false, GTFSv2_Realtime_TripDescriptor_init_zero, false, GTFSv2_Realtime_Position_init_zero, false, 0, false, _GTFSv2_Realtime_VehiclePosition_VehicleStopStatus_MIN, false, 0, false, _GTFSv2_Realtime_VehiclePosition_CongestionLevel_MIN, {{NULL}, NULL}, false, GTFSv2_Realtime_VehicleDescriptor_init_zero, false, _GTFSv2_Realtime_VehiclePosition_OccupancyStatus_MIN, false, 0, NULL}
#define GTFSv2_Realtime_Alert_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, false, _GTFSv2_Realtime_Alert_Cause_MIN, false, _GTFSv2_Realtime_Alert_Effect_MIN, false, GTFSv2_Realtime_TranslatedString_init_zero, false, GTFSv2_Realtime_TranslatedString_init_zero, false, GTFSv2_Realtime_TranslatedString_init_zero, false, GTFSv2_Realtime_TranslatedString_init_zero, false, GTFSv2_Realtime_TranslatedString_init_zero, false, _GTFSv2_Realtime_Alert_SeverityLevel_MIN, NULL}
#define GTFSv2_Realtime_TimeRange_init_zero      {false, 0, false, 0, NULL}
#define GTFSv2_Realtime_Position_init_zero       {0, 0, false, 0, false, 0, false, 0, NULL}
#define GTFSv2_Realtime_TripDescriptor_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _GTFSv2_Realtime_TripDescriptor_ScheduleRelationship_MIN, {{NULL}, NULL}, false, 0, NULL}
#define GTFSv2_Realtime_VehicleDescriptor_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_EntitySelector_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, GTFSv2_Realtime_TripDescriptor_init_zero, {{NULL}, NULL}, false, 0, NULL}
#define GTFSv2_Realtime_TranslatedString_init_zero {{{NULL}, NULL}, NULL}
#define GTFSv2_Realtime_TranslatedString_Translation_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define GTFSv2_Realtime_FeedHeader_gtfs_realtime_version_tag 1
#define GTFSv2_Realtime_FeedHeader_incrementality_tag 2
#define GTFSv2_Realtime_FeedHeader_timestamp_tag 3
#define GTFSv2_Realtime_FeedMessage_header_tag   1
#define GTFSv2_Realtime_FeedMessage_entity_tag   2
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_delay_tag 1
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_time_tag 2
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_uncertainty_tag 3
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_stop_sequence_tag 1
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_arrival_tag 2
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_departure_tag 3
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_stop_id_tag 4
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_schedule_relationship_tag 5
#define GTFSv2_Realtime_TimeRange_start_tag      1
#define GTFSv2_Realtime_TimeRange_end_tag        2
#define GTFSv2_Realtime_Position_latitude_tag    1
#define GTFSv2_Realtime_Position_longitude_tag   2
#define GTFSv2_Realtime_Position_bearing_tag     3
#define GTFSv2_Realtime_Position_odometer_tag    4
#define GTFSv2_Realtime_Position_speed_tag       5
#define GTFSv2_Realtime_TripDescriptor_trip_id_tag 1
#define GTFSv2_Realtime_TripDescriptor_start_time_tag 2
#define GTFSv2_Realtime_TripDescriptor_start_date_tag 3
#define GTFSv2_Realtime_TripDescriptor_schedule_relationship_tag 4
#define GTFSv2_Realtime_TripDescriptor_route_id_tag 5
#define GTFSv2_Realtime_TripDescriptor_direction_id_tag 6
#define GTFSv2_Realtime_VehicleDescriptor_id_tag 1
#define GTFSv2_Realtime_VehicleDescriptor_label_tag 2
#define GTFSv2_Realtime_VehicleDescriptor_license_plate_tag 3
#define GTFSv2_Realtime_TripUpdate_trip_tag      1
#define GTFSv2_Realtime_TripUpdate_stop_time_update_tag 2
#define GTFSv2_Realtime_TripUpdate_vehicle_tag   3
#define GTFSv2_Realtime_TripUpdate_timestamp_tag 4
#define GTFSv2_Realtime_TripUpdate_delay_tag     5
#define GTFSv2_Realtime_VehiclePosition_trip_tag 1
#define GTFSv2_Realtime_VehiclePosition_position_tag 2
#define GTFSv2_Realtime_VehiclePosition_current_stop_sequence_tag 3
#define GTFSv2_Realtime_VehiclePosition_current_status_tag 4
#define GTFSv2_Realtime_VehiclePosition_timestamp_tag 5
#define GTFSv2_Realtime_VehiclePosition_congestion_level_tag 6
#define GTFSv2_Realtime_VehiclePosition_stop_id_tag 7
#define GTFSv2_Realtime_VehiclePosition_vehicle_tag 8
#define GTFSv2_Realtime_VehiclePosition_occupancy_status_tag 9
#define GTFSv2_Realtime_VehiclePosition_occupancy_percentage_tag 10
#define GTFSv2_Realtime_EntitySelector_agency_id_tag 1
#define GTFSv2_Realtime_EntitySelector_route_id_tag 2
#define GTFSv2_Realtime_EntitySelector_route_type_tag 3
#define GTFSv2_Realtime_EntitySelector_trip_tag  4
#define GTFSv2_Realtime_EntitySelector_stop_id_tag 5
#define GTFSv2_Realtime_EntitySelector_direction_id_tag 6
#define GTFSv2_Realtime_TranslatedString_translation_tag 1
#define GTFSv2_Realtime_Alert_active_period_tag  1
#define GTFSv2_Realtime_Alert_informed_entity_tag 5
#define GTFSv2_Realtime_Alert_cause_tag          6
#define GTFSv2_Realtime_Alert_effect_tag         7
#define GTFSv2_Realtime_Alert_url_tag            8
#define GTFSv2_Realtime_Alert_header_text_tag    10
#define GTFSv2_Realtime_Alert_description_text_tag 11
#define GTFSv2_Realtime_Alert_tts_header_text_tag 12
#define GTFSv2_Realtime_Alert_tts_description_text_tag 13
#define GTFSv2_Realtime_Alert_severity_level_tag 14
#define GTFSv2_Realtime_FeedEntity_id_tag        1
#define GTFSv2_Realtime_FeedEntity_is_deleted_tag 2
#define GTFSv2_Realtime_FeedEntity_trip_update_tag 3
#define GTFSv2_Realtime_FeedEntity_vehicle_tag   4
#define GTFSv2_Realtime_FeedEntity_alert_tag     5
#define GTFSv2_Realtime_TranslatedString_Translation_text_tag 1
#define GTFSv2_Realtime_TranslatedString_Translation_language_tag 2

/* Struct field encoding specification for nanopb */
#define GTFSv2_Realtime_FeedMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  entity,            2) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_FeedMessage_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_FeedMessage_DEFAULT NULL
#define GTFSv2_Realtime_FeedMessage_header_MSGTYPE GTFSv2_Realtime_FeedHeader
#define GTFSv2_Realtime_FeedMessage_entity_MSGTYPE GTFSv2_Realtime_FeedEntity

#define GTFSv2_Realtime_FeedHeader_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   gtfs_realtime_version,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    incrementality,    2) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         3) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_FeedHeader_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_FeedHeader_DEFAULT NULL

#define GTFSv2_Realtime_FeedEntity_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, BOOL,     is_deleted,        2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trip_update,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vehicle,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  alert,             5) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_FeedEntity_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_FeedEntity_DEFAULT (const pb_byte_t*)"\x10\x00\x00"
#define GTFSv2_Realtime_FeedEntity_trip_update_MSGTYPE GTFSv2_Realtime_TripUpdate
#define GTFSv2_Realtime_FeedEntity_vehicle_MSGTYPE GTFSv2_Realtime_VehiclePosition
#define GTFSv2_Realtime_FeedEntity_alert_MSGTYPE GTFSv2_Realtime_Alert

#define GTFSv2_Realtime_TripUpdate_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  trip,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  stop_time_update,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vehicle,           3) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         4) \
X(a, STATIC,   OPTIONAL, INT32,    delay,             5) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TripUpdate_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TripUpdate_DEFAULT NULL
#define GTFSv2_Realtime_TripUpdate_trip_MSGTYPE GTFSv2_Realtime_TripDescriptor
#define GTFSv2_Realtime_TripUpdate_stop_time_update_MSGTYPE GTFSv2_Realtime_TripUpdate_StopTimeUpdate
#define GTFSv2_Realtime_TripUpdate_vehicle_MSGTYPE GTFSv2_Realtime_VehicleDescriptor

#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    delay,             1) \
X(a, STATIC,   OPTIONAL, INT64,    time,              2) \
X(a, STATIC,   OPTIONAL, INT32,    uncertainty,       3) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_DEFAULT NULL

#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   stop_sequence,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arrival,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  departure,         3) \
X(a, CALLBACK, OPTIONAL, STRING,   stop_id,           4) \
X(a, STATIC,   OPTIONAL, UENUM,    schedule_relationship,   5) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_DEFAULT NULL
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_arrival_MSGTYPE GTFSv2_Realtime_TripUpdate_StopTimeEvent
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_departure_MSGTYPE GTFSv2_Realtime_TripUpdate_StopTimeEvent

#define GTFSv2_Realtime_VehiclePosition_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trip,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   current_stop_sequence,   3) \
X(a, STATIC,   OPTIONAL, UENUM,    current_status,    4) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         5) \
X(a, STATIC,   OPTIONAL, UENUM,    congestion_level,   6) \
X(a, CALLBACK, OPTIONAL, STRING,   stop_id,           7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vehicle,           8) \
X(a, STATIC,   OPTIONAL, UENUM,    occupancy_status,   9) \
X(a, STATIC,   OPTIONAL, UINT32,   occupancy_percentage,  10) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_VehiclePosition_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_VehiclePosition_DEFAULT (const pb_byte_t*)"\x20\x02\x00"
#define GTFSv2_Realtime_VehiclePosition_trip_MSGTYPE GTFSv2_Realtime_TripDescriptor
#define GTFSv2_Realtime_VehiclePosition_position_MSGTYPE GTFSv2_Realtime_Position
#define GTFSv2_Realtime_VehiclePosition_vehicle_MSGTYPE GTFSv2_Realtime_VehicleDescriptor

#define GTFSv2_Realtime_Alert_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  active_period,     1) \
X(a, CALLBACK, REPEATED, MESSAGE,  informed_entity,   5) \
X(a, STATIC,   OPTIONAL, UENUM,    cause,             6) \
X(a, STATIC,   OPTIONAL, UENUM,    effect,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  url,               8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header_text,      10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  description_text,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tts_header_text,  12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tts_description_text,  13) \
X(a, STATIC,   OPTIONAL, UENUM,    severity_level,   14) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_Alert_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_Alert_DEFAULT (const pb_byte_t*)"\x30\x01\x38\x08\x70\x01\x00"
#define GTFSv2_Realtime_Alert_active_period_MSGTYPE GTFSv2_Realtime_TimeRange
#define GTFSv2_Realtime_Alert_informed_entity_MSGTYPE GTFSv2_Realtime_EntitySelector
#define GTFSv2_Realtime_Alert_url_MSGTYPE GTFSv2_Realtime_TranslatedString
#define GTFSv2_Realtime_Alert_header_text_MSGTYPE GTFSv2_Realtime_TranslatedString
#define GTFSv2_Realtime_Alert_description_text_MSGTYPE GTFSv2_Realtime_TranslatedString
#define GTFSv2_Realtime_Alert_tts_header_text_MSGTYPE GTFSv2_Realtime_TranslatedString
#define GTFSv2_Realtime_Alert_tts_description_text_MSGTYPE GTFSv2_Realtime_TranslatedString

#define GTFSv2_Realtime_TimeRange_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   start,             1) \
X(a, STATIC,   OPTIONAL, UINT64,   end,               2) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TimeRange_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TimeRange_DEFAULT NULL

#define GTFSv2_Realtime_Position_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    latitude,          1) \
X(a, STATIC,   REQUIRED, FLOAT,    longitude,         2) \
X(a, STATIC,   OPTIONAL, FLOAT,    bearing,           3) \
X(a, STATIC,   OPTIONAL, DOUBLE,   odometer,          4) \
X(a, STATIC,   OPTIONAL, FLOAT,    speed,             5) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_Position_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_Position_DEFAULT NULL

#define GTFSv2_Realtime_TripDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   trip_id,           1) \
X(a, CALLBACK, OPTIONAL, STRING,   start_time,        2) \
X(a, CALLBACK, OPTIONAL, STRING,   start_date,        3) \
X(a, STATIC,   OPTIONAL, UENUM,    schedule_relationship,   4) \
X(a, CALLBACK, OPTIONAL, STRING,   route_id,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   direction_id,      6) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TripDescriptor_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TripDescriptor_DEFAULT NULL

#define GTFSv2_Realtime_VehicleDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   id,                1) \
X(a, CALLBACK, OPTIONAL, STRING,   label,             2) \
X(a, CALLBACK, OPTIONAL, STRING,   license_plate,     3) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_VehicleDescriptor_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_VehicleDescriptor_DEFAULT NULL

#define GTFSv2_Realtime_EntitySelector_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   agency_id,         1) \
X(a, CALLBACK, OPTIONAL, STRING,   route_id,          2) \
X(a, STATIC,   OPTIONAL, INT32,    route_type,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trip,              4) \
X(a, CALLBACK, OPTIONAL, STRING,   stop_id,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   direction_id,      6) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_EntitySelector_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_EntitySelector_DEFAULT NULL
#define GTFSv2_Realtime_EntitySelector_trip_MSGTYPE GTFSv2_Realtime_TripDescriptor

#define GTFSv2_Realtime_TranslatedString_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  translation,       1) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TranslatedString_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TranslatedString_DEFAULT NULL
#define GTFSv2_Realtime_TranslatedString_translation_MSGTYPE GTFSv2_Realtime_TranslatedString_Translation

#define GTFSv2_Realtime_TranslatedString_Translation_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   text,              1) \
X(a, CALLBACK, OPTIONAL, STRING,   language,          2) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,      1000)
#define GTFSv2_Realtime_TranslatedString_Translation_CALLBACK pb_default_field_callback
#define GTFSv2_Realtime_TranslatedString_Translation_DEFAULT NULL

extern const pb_msgdesc_t GTFSv2_Realtime_FeedMessage_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_FeedHeader_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_FeedEntity_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TripUpdate_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TripUpdate_StopTimeEvent_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TripUpdate_StopTimeUpdate_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_VehiclePosition_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_Alert_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TimeRange_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_Position_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TripDescriptor_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_VehicleDescriptor_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_EntitySelector_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TranslatedString_msg;
extern const pb_msgdesc_t GTFSv2_Realtime_TranslatedString_Translation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GTFSv2_Realtime_FeedMessage_fields &GTFSv2_Realtime_FeedMessage_msg
#define GTFSv2_Realtime_FeedHeader_fields &GTFSv2_Realtime_FeedHeader_msg
#define GTFSv2_Realtime_FeedEntity_fields &GTFSv2_Realtime_FeedEntity_msg
#define GTFSv2_Realtime_TripUpdate_fields &GTFSv2_Realtime_TripUpdate_msg
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_fields &GTFSv2_Realtime_TripUpdate_StopTimeEvent_msg
#define GTFSv2_Realtime_TripUpdate_StopTimeUpdate_fields &GTFSv2_Realtime_TripUpdate_StopTimeUpdate_msg
#define GTFSv2_Realtime_VehiclePosition_fields &GTFSv2_Realtime_VehiclePosition_msg
#define GTFSv2_Realtime_Alert_fields &GTFSv2_Realtime_Alert_msg
#define GTFSv2_Realtime_TimeRange_fields &GTFSv2_Realtime_TimeRange_msg
#define GTFSv2_Realtime_Position_fields &GTFSv2_Realtime_Position_msg
#define GTFSv2_Realtime_TripDescriptor_fields &GTFSv2_Realtime_TripDescriptor_msg
#define GTFSv2_Realtime_VehicleDescriptor_fields &GTFSv2_Realtime_VehicleDescriptor_msg
#define GTFSv2_Realtime_EntitySelector_fields &GTFSv2_Realtime_EntitySelector_msg
#define GTFSv2_Realtime_TranslatedString_fields &GTFSv2_Realtime_TranslatedString_msg
#define GTFSv2_Realtime_TranslatedString_Translation_fields &GTFSv2_Realtime_TranslatedString_Translation_msg

/* Maximum encoded size of messages (where known) */
/* GTFSv2_Realtime_FeedMessage_size depends on runtime parameters */
/* GTFSv2_Realtime_FeedHeader_size depends on runtime parameters */
/* GTFSv2_Realtime_FeedEntity_size depends on runtime parameters */
/* GTFSv2_Realtime_TripUpdate_size depends on runtime parameters */
/* GTFSv2_Realtime_TripUpdate_StopTimeUpdate_size depends on runtime parameters */
/* GTFSv2_Realtime_VehiclePosition_size depends on runtime parameters */
/* GTFSv2_Realtime_Alert_size depends on runtime parameters */
/* GTFSv2_Realtime_TripDescriptor_size depends on runtime parameters */
/* GTFSv2_Realtime_VehicleDescriptor_size depends on runtime parameters */
/* GTFSv2_Realtime_EntitySelector_size depends on runtime parameters */
/* GTFSv2_Realtime_TranslatedString_size depends on runtime parameters */
/* GTFSv2_Realtime_TranslatedString_Translation_size depends on runtime parameters */
#define GTFSV2_REALTIME_GTFS_REALTIME_PB_H_MAX_SIZE GTFSv2_Realtime_TripUpdate_StopTimeEvent_size
#define GTFSv2_Realtime_Position_size            29
#define GTFSv2_Realtime_TimeRange_size           22
#define GTFSv2_Realtime_TripUpdate_StopTimeEvent_size 33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
