/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "gtfs-realtime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GTFSv2_Realtime_FeedMessage, GTFSv2_Realtime_FeedMessage, 2)


PB_BIND(GTFSv2_Realtime_FeedHeader, GTFSv2_Realtime_FeedHeader, 2)


PB_BIND(GTFSv2_Realtime_FeedEntity, GTFSv2_Realtime_FeedEntity, 2)


PB_BIND(GTFSv2_Realtime_TripUpdate, GTFSv2_Realtime_TripUpdate, 2)


PB_BIND(GTFSv2_Realtime_TripUpdate_StopTimeEvent, GTFSv2_Realtime_TripUpdate_StopTimeEvent, 2)


PB_BIND(GTFSv2_Realtime_TripUpdate_StopTimeUpdate, GTFSv2_Realtime_TripUpdate_StopTimeUpdate, 2)


PB_BIND(GTFSv2_Realtime_VehiclePosition, GTFSv2_Realtime_VehiclePosition, 2)


PB_BIND(GTFSv2_Realtime_Alert, GTFSv2_Realtime_Alert, 2)


PB_BIND(GTFSv2_Realtime_TimeRange, GTFSv2_Realtime_TimeRange, 2)


PB_BIND(GTFSv2_Realtime_Position, GTFSv2_Realtime_Position, 2)


PB_BIND(GTFSv2_Realtime_TripDescriptor, GTFSv2_Realtime_TripDescriptor, 2)


PB_BIND(GTFSv2_Realtime_VehicleDescriptor, GTFSv2_Realtime_VehicleDescriptor, 2)


PB_BIND(GTFSv2_Realtime_EntitySelector, GTFSv2_Realtime_EntitySelector, 2)


PB_BIND(GTFSv2_Realtime_TranslatedString, GTFSv2_Realtime_TranslatedString, 2)


PB_BIND(GTFSv2_Realtime_TranslatedString_Translation, GTFSv2_Realtime_TranslatedString_Translation, 2)





















#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

